services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - chromadb
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - app-net
    environment:
      # Analysis
      - ENV=dev
      - GLOBAL_LOG_LEVEL=DEBUG
      # Configuration
      - ENABLE_PERSISTENT_CONFIG=false
      # Database
      - VECTOR_DB=chroma
      - CHROMA_HTTP_HOST=chromadb
      - CHROMA_HTTP_PORT=8000      
      # OAuth Configuration; Callback=http://localhost:3000/oauth/oidc/callback
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_CLIENT_ID=4991ac94-8bfc-4631-9661-8f7890bd9d43
      - OAUTH_CLIENT_SECRET=dk78Q~nvrXxZe7df~neJo31Y9CFl-COy-DkrWar~
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - OAUTH_PROVIDER_NAME=Azure Entra ID
      - OAUTH_SCOPES=openid profile email User.Read
      - OPENID_PROVIDER_URL=https://login.microsoftonline.com/3394be55-693a-4404-add0-aef6598abcec/v2.0/.well-known/openid-configuration
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      - OAUTH_EMAIL_CLAIM=upn
 
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    restart: always
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pipelines:/app/pipelines
    networks:
      - app-net
    environment:
      - PIPELINES_URLS=https://github.com/g4-api/g4-webui-pipelines/blob/main/pipelines/python_code_pipeline.py

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    networks:
      - app-net

volumes:
  open-webui:
  pipelines:

networks:
  app-net:
    driver: bridge