version: "3.8"

x-common-token: &common-token
  TOKEN: "3xezq5Yc33laNOPNP8yCsK33vQcQZ87E/zyLNNscYNeqvKTHAm9C3wAEDQV7X9+fuuHPhafDNXbSFgsbKmCncCKm7DRE5A6JtFSd90DNujujbQ3vLG4/4uSVCR76Z6VguIDSvRZ/pJTHCzBc9NNI/eb5fLHcjXyYrilm9NC7VTD/HOlgGC5CL+oFhHoR8s10YuI9QpRioZbyDHysFumpAAv3/PG/p/QBKNoQpjtsUgMytrnqr3m1bgyXITG0u5AUR2VpZLCXQO6MxU7kwLwvdNGXUDfajBVT29KyjXUEWN9dK0R38XmgZFQ7orkKfN2z0x2SMfC5mvTDM6as+/kYWFAvpqOZDhZ95sgQWp/zGig="

services:
  volume-cleanup-bot-a:
    image: g4-partition-cleanup-bot:latest

    container_name: volume-cleanup-bot-37e0b6fb-5557-4c2d-b17d-ce986484251f

    ports:
      - "49215:9213"

    volumes:
      - "C:/g4-bots-volume-a:/bots"

    environment:
      <<: *common-token
      BOT_ID: "1747406857573"
      CALLBACK_INGRESS: "http://host.docker.internal:49215"
      CALLBACK_URI: "http://host.docker.internal:49215"
      CLEANUP_BOT_INTERVAL_TIME: "5"
      CLEANUP_BOT_NUNBER_OF_FILES: "3"
      HUB_URI: "http://host.docker.internal:9944"

    restart: unless-stopped

  volume-cleanup-bot-b:
    image: g4-partition-cleanup-bot:latest

    container_name: volume-cleanup-bot-b2f305f3-1039-4b55-96d9-b3ac7d346c99

    ports:
      - "49216:9213"

    volumes:
      - "C:/g4-bots-volume-b:/bots"

    environment:
      <<: *common-token
      BOT_ID: "2747406857573"
      CALLBACK_INGRESS: "http://host.docker.internal:49216"
      CALLBACK_URI: "http://host.docker.internal:49216"
      CLEANUP_BOT_INTERVAL_TIME: "10"
      CLEANUP_BOT_NUNBER_OF_FILES: "5"
      HUB_URI: "http://host.docker.internal:9944"

    restart: unless-stopped
