version: "3.8"

# Shared values
x-common-env: &common-env
  TOKEN: "3xezq5Yc33laNOPNP8yCsK33vQcQZ87E/zyLNNscYNeqvKTHAm9C3wAEDQV7X9+fuuHPhafDNXbSFgsbKmCncCKm7DRE5A6JtFSd90DNujujbQ3vLG4/4uSVCR76Z6VguIDSvRZ/pJTHCzBc9NNI/eb5fLHcjXyYrilm9NC7VTD/HOlgGC5CL+oFhHoR8s10YuI9QpRioZbyDHysFumpAAv3/PG/p/QBKNoQpjtsUgMytrnqr3m1bgyXITG0u5AUR2VpZLCXQO6MxU7kwLwvdNGXUDfajBVT29KyjXUEWN9dK0R38XmgZFQ7orkKfN2z0x2SMfC5mvTDM6as+/kYWFAvpqOZDhZ95sgQWp/zGig="

x-common-volumes: &common-volumes
  - "C:/g4-bots-volume:/bots"

services:
  g4-cron-bot-a:
    image: g4-cron-bot:latest

    container_name: g4-cron-bot-6ffdc309-cf05-4b51-a22f-258b4a6ea0c0

    ports:
      - "49213:9213"
    volumes: *common-volumes

    environment:
      <<: *common-env
      BOT_ID: "1747331681414"
      BOT_NAME: "g4-cron-bot"
      CALLBACK_INGRESS: "http://host.docker.internal:49213"
      CALLBACK_URI: "http://host.docker.internal:49213"
      CRON_BOT_SCHEDULES: "* * * * *,*/5 * * * *"
      DRIVER_BINARIES: "http://host.docker.internal:4444/wd/hub"
      HUB_URI: "http://host.docker.internal:9944"
      SAVE_ERRORS: "True"
      SAVE_RESPONSE: "True"

    restart: unless-stopped

  g4-cron-bot-b:
    image: g4-cron-bot:latest

    container_name: g4-cron-bot-c4da7f00-a2e4-4f66-8f98-81f5f536a1b1

    ports:
      - "49214:9213"
    volumes: *common-volumes

    environment:
      <<: *common-env
      BOT_ID: "1747331681415"
      BOT_NAME: "g4-cron-bot"
      CALLBACK_INGRESS: "http://host.docker.internal:49214"
      CALLBACK_URI: "http://host.docker.internal:49214"
      CRON_SCHEDULES: "* * * * *,*/10 * * * *"
      DRIVER_BINARIES: "http://host.docker.internal:4444/wd/hub"
      HUB_URI: "http://host.docker.internal:9944"
      SAVE_ERRORS: "True"
      SAVE_RESPONSE: "True"

    restart: unless-stopped
