[node]
detect-drivers = false

[relay]
url = "http://localhost:9513"
status-endpoint = "/status"
protocol-version = "HTTP/1.1"
configs = [
  "10", "{\"browserName\": \"chrome\", \"platformName\": \"windows\"}"
]